before_install:
- sudo apt-get update -qq
- sudo apt-get install -y pandoc
- sudo apt-get install -y texlive-full
- sudo apt-get install -y texlive-xetex
- chmod u+x ./travis/build.sh
- chmod u+x ./travis/publish.sh
script: "./travis/build.sh"
after_success:
- "./travis/publish.sh"
env:
  global:
  - GH_USER_NAME: dusterdieck-enterprise
  - GH_PROJECT_NAME: testbed
  - GIT_AUTHOR_NAME: Travis
  - GIT_AUTHOR_EMAIL: npreply@travis-ci.org
  - RESULT_PDF_PATH=$TRAVIS_BUILD_DIR/resources.pdf
  - TZ="America/New_York"
  - secure: GBep4wsa6t4GNMks6+KQrn9M7fBw14mBrAJBUCBGwe4h+kO4NYSbB1stEg/7BFfFpVNpY1DBblXtRBk/CpDMJs4pBCefEQnI3T8Bf58xZ5uQrbqDGf3NpX3hHqhWnWNChePIf4Uj+TzMFHVg8pnGW16XnGGbJsn6jBJuX9HHPdzzCNvfyKnGpFoEyzFd+DIzvlUhT+sDQsmaQ3tyEp0dh+WJP+zqfEnsGVOcvHpudpuBTfXQ9rUVC0KcUWuXddpXi0L4cdneAR42giMxaXU5SOGurAGNSi90EdZV5gX2J5obs5sNvFNIW0+z6qWQ3yNld47j1jlO4dDSo859wv7S0T+33qaMMkKJPXEi+D/WH/qjbjwzn2/lBoNapuBoK8vRW2Ivl/At25d353XmxlVVxmlWRMPcK0r95py+FDTRs0+d41VoT2rkybCzMZoJVs6RLFbA7NoIRTRJ6nRexZcpR+4/INBlJ9CP8YH8dn9RDtNS/WJBG5jyxekT7fJ5aNVLRu/wQA4a1EOnJVneauWclJFRBlVxtcYquDn4UReUtfDArYTLftamc2mNqPdbAuFdOf31kRJL8KssVlSq6wdkb5M44A+INuS4xUuOlCJLOgP9axFkhjG+I94xxgssmLKS3ruxTfb0hcckknrmhEgP+Ace5OPA0s7ZfBZBRulqdu4=
